ADVANCED: false
CELL_AREA: 1541818.0
CLK_FREQ_MHZ: 50.0
CLK_PORT_NAME: clock
CODE_SOURCE: UPLOAD
CORE_AREA: 0.0
CORE_BBOX: 10.004500000000007 9.904499999999985 1251.6045 1251.7044999999998
CORE_UTIL: 0.9934059381484985
CURRENT_STEP: soc
DEF_FILE: /taskData/task_4456/17_filler/ip1_SimpleEdgeAiSoC_filler.def
DIE_AREA: 0.0
DIE_BBOX: 0 0 1261.609 1261.609
ECOS_PROJECT_ID: '2017'
ECOS_TASK_ID: '4456'
ECOS_TASK_TYPE: soc
FAST_ROUTE: false
FAST_SIGNOFF: true
FILELIST: ''
FINISHED_STEP: soc
GDS_FILE: /taskData/task_4456/ip1_SimpleEdgeAiSoC_signoff.gds
IEDA_ECOS_NOTIFICATION_SECRET: '1234567890'
IEDA_ECOS_NOTIFICATION_URL: http://0.0.0.0:9444/apis/v1/ieda/running_notify
LAST_UPDATE_TIME: '20251202_154339'
MAX_FANOUT: 32
MAX_ITERATIVE: 2000
NETLIST_FILE: /taskData/task_4456/17_filler/ip1_SimpleEdgeAiSoC_filler.v
NUM_EXECUTED_STEPS: 21
PDK_NAME: ics55
RESULT_DIR: /taskData/task_4456
RTL_FILE:
- /projectData/project_2017/source/SimpleEdgeAiSoC.sv
SDC_FILE: /home/user/RTL2GDS/tools/default.sdc
TARGET_DENSITY: 0.3
TARGET_OVERFLOW: 0.1
TOP_NAME: ip1_SimpleEdgeAiSoC
USE_FIXED_BBOX: false
